spring:
  datasource:
    url: jdbc:mysql:///genie-example?rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
logging:
  level:
    io.github.genie.sql: debug